### ISSUE TITLE
How can a customer price be 0?

### ISSUE THREAD

**Issue by csabashapr** [snscripts/itc-reporter#5]
The Reporter API gives back a Subscription report for a given day with some records where the  "Customer Price" is 0. Do you know how is it possible? Additionally : the Active Free Trials field can contain huge values like "17". Do you know how is it possible?

Thanks!

**Comment by fedoco** [comment]
These are questions for Apple's developer support, don't you think?

**Comment by mikebarlow** [comment]
Hi,
This is likely a question for Apple Support rather than something specific to this package. If there is a problem here, it's likely that Apple updated the CSV responses which means the package could be assigning the columns to the wrong variables.

I'm unable to test this at the moment. Are you able to login to your iTunes Connect Account and download the reports via the control panel and see if the results match what the package is returning?
